# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  name: Default
  vmImage: ubuntu-latest

stages:
- stage: "Checkout"
  displayName: "Checkout source code"
  jobs:
  - job: checkout
    steps:
    - script: |
        echo "Checkout source code"
      displayName: "Checkout source code"
- stage: "BuildProject"
  displayName: "Build Project"
  dependsOn: Checkout
  jobs:
  - job: Build
    steps:
    - script: |
        echo "Move to core-service"
        cd core-service
        pwd
        docker build . -t core-service:v1
      displayName: "Build Project"
- stage: 
  displayName: "Scan Project"
  dependsOn: Checkout
  jobs:
    - deployment: 
      environment: wait
      displayName: "Scan code with gitleaks"
      strategy:
        runOnce:
          deploy:
            steps:
            - task: Gitleaks@3
              name: scan
              inputs:
                scanlocation: '$(Build.SourcesDirectory)/core-service'
                configtype: 'predefined'
                predefinedconfigfile: 'GitleaksUdmCombo.toml'
                reportformat: 'sarif'
                scanmode: 'directory'
              displayName: "Scan for password or hardcode"
              continueOnError: true
- stage: 
  displayName: "Scan Image"
  dependsOn: BuildProject
  jobs:
    - deployment: 
      environment: dev
      displayName: "Scan image with trivy"
      condition: |
              and(
                succeeded(),
                startsWith(variables['Build.SourceBranch'], 'refs/heads/master')
              )
      strategy:
        runOnce:
          deploy:
            steps:
              - powershell: |
                        $url = "https://github.com/aquasecurity/trivy/releases/download/v$version/trivy_${version}_windows-64bit.zip"
                        Write-Host "Download Trivy from $url"
                        Invoke-WebRequest $url -OutFile trivy.zip
                        Expand-Archive trivy.zip -DestinationPath .
                        .\trivy.exe image maven:3.9.14-eclipse-temurin-17 --severity HIGH,CRITICAL --exit-code 1
                displayName: "Scan Docker Image"