apiVersion: v1
kind: Service
metadata:
  name: redis-master-external
  namespace: redis
spec:
  type: NodePort
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30380
  selector:
    app.kubernetes.io/instance: redis-sentinel
    app.kubernetes.io/name: redis
    role: master
