apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - args:
            - minio server /data --console-address :9090
          command:
            - /bin/bash
            - -c
          env:
            - name: MINIO_ACCESS_KEY
              value: sMw5abaBopFiyVHBlWwv
            - name: MINIO_SECRET_KEY
              value: RjIlpoxKyLG8pMZJPZM4W5Q08yRK8Yzygoc1F2iz
          image: minio/minio:RELEASE.2023-10-24T04-42-36Z.fips
          imagePullPolicy: IfNotPresent
          name: minio
          ports:
            - containerPort: 9000
              protocol: TCP
            - containerPort: 9090
              protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          volumeMounts:
            - mountPath: /data
              name: minio-data
      volumes:
        - name: minio-data
          persistentVolumeClaim:
            claimName: nfs-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: minio
  name: minio-nodeport
spec:
  ports:
    - nodePort: 8054
      port: 9000
      protocol: TCP
      targetPort: 9000
      name: api-nodeport
    - nodePort: 8077
      port: 9090
      protocol: TCP
      targetPort: 9090
      name: console-nodeport
  selector:
    app: minio
  type: NodePort
